# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: lazyado
    main: ./cmd/lazyado/main.go
    binary: lazyado
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    goarm:
      - 7

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{- end }}{{- if .Arm }}v{{ .Arm }}{{- end }}'

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

# snapshot.name_template deprecated; rely on GoReleaser defaults for snapshot naming

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore"
